# Generated by Django 4.0.9 on 2023-02-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storymodel',
            name='views',
        ),
    ]
