# Generated by Django 4.0.9 on 2023-02-15 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0002_remove_storymodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
