# Generated by Django 4.0.9 on 2023-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_storymodel_created_at_storymodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
