# Generated by Django 4.0.9 on 2023-02-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0004_alter_storymodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storys.storymodel'),
        ),
    ]
