# Generated by Django 4.0.9 on 2023-02-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0005_alter_tagmodel_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='storys.storymodel'),
        ),
    ]
