# Generated by Django 4.0.9 on 2023-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0006_alter_tagmodel_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='story',
        ),
        migrations.AddField(
            model_name='storymodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storymodel',
            name='tag',
            field=models.ManyToManyField(to='storys.tagmodel'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
