# Generated by Django 4.0.9 on 2023-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0007_remove_tagmodel_story_storymodel_slug_storymodel_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
