# Generated by Django 4.0.9 on 2023-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0008_alter_storymodel_slug_alter_tagmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
